[home_work_11] add test db, repository, dao, mappers
artem-inkaz/The_Movie_DB pull request #11
Opened 2024-09-24 16:26 UTC by artem-inkaz

2024-09-25 12:02 UTC, AndroidStudentClub requested changes
Немного небрежно написано (не совпадают имена тестов/названия переменных) скорее всего торопился. А так в целом верно, коменты написал по улучшению

2024-09-25 12:02 UTC, AndroidStudentClub commented on app/build.gradle
> +    androidTestImplementation "junit:junit:4.13.2"
В константы, иначе иногда версии могут конфликтовать и так сложнее обновлять/поддерживать проект)

2024-09-25 12:02 UTC, AndroidStudentClub commented on app/src/test/java/ru/androidschool/intensiv/mappers/GenreMapperDtoTest.kt
> +    fun `test actor mapper dto success`() {
Только тут название не совпадает с тем что здесь проверяется (Genre)

2024-09-25 12:02 UTC, AndroidStudentClub commented on app/src/test/java/ru/androidschool/intensiv/mappers/GenreMapperDtoTest.kt
> +    fun `test actors mapper dto success`() {
Только тут название не совпадает с тем что здесь проверяется (Genre)

2024-09-25 12:02 UTC, AndroidStudentClub commented on app/src/test/java/ru/androidschool/intensiv/repository/BaseRepositoryTest.kt
> +open class BaseRepositoryTest {
Обычно в Unit тестах стараются не использовать наследование. Для переиспользования логики здесь можно попробовать создать кастомный Rule (в презентации есть пример) Методы Rule будут также вызываться при старте тестов и в конце, но у нас уже не будет наследования, то есть вместо наследования мы переходим к композиции, что делает тест более простыми, независимыми и не зависящими от общего стейта/данных

2024-09-25 12:02 UTC, AndroidStudentClub commented on app/src/test/java/ru/androidschool/intensiv/repository/MovieActorRepositoryTest.kt
> +       val repoSize = repository.getByMovieId(testProduct[0].movieId.toString()).test().assertNoErrors().values().size
Названия не очень. Это же кол-во фильмов, лучше так и писать moviesSize/MoviesIdSize

2024-09-25 12:02 UTC, AndroidStudentClub commented on app/src/test/java/ru/androidschool/intensiv/repository/MovieActorRepositoryTest.kt
> +        val testProduct = mockMovieActor
Название так себе

2024-09-25 12:02 UTC, AndroidStudentClub commented on core/storage/src/test/java/ru/androidschool/intensiv/core/storage/database/GenreDaoTest.kt
> +        val taskSize = databaseRule.appDatabase.getGenreDao().getAll().test().values().first()?.size
Получаешь жанры, а в названии tasks, сложно понять что тестируешь (название тоже не соответствует)

2024-09-26 07:26 UTC, artem-inkaz commented on app/src/test/java/ru/androidschool/intensiv/mappers/GenreMapperDtoTest.kt
> +    fun `test actor mapper dto success`() {
done

2024-09-26 07:26 UTC, artem-inkaz commented on app/src/test/java/ru/androidschool/intensiv/mappers/GenreMapperDtoTest.kt
> +    fun `test actors mapper dto success`() {
done

2024-09-26 07:28 UTC, artem-inkaz commented on app/src/test/java/ru/androidschool/intensiv/repository/MovieActorRepositoryTest.kt
> +        val testProduct = mockMovieActor
done

2024-09-26 07:29 UTC, artem-inkaz commented on core/storage/src/test/java/ru/androidschool/intensiv/core/storage/database/GenreDaoTest.kt
> +        val taskSize = databaseRule.appDatabase.getGenreDao().getAll().test().values().first()?.size
done

2024-09-27 04:47 UTC, merged