Feature/home work 2
artem-inkaz/The_Movie_DB pull request #2
Opened 2024-08-14 08:58 UTC by artem-inkaz

Добавлена логика получения фильмов, сериалов, экран детализации фильмов

2024-08-15 15:25 UTC, AndroidStudentClub requested changes
Проверил, неплохо, но надо избегать дублирования кода, по возможности выносить в методы логику/константы использовать/базовый классы/экстеншны

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/build.gradle
> +    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
Версии библиотек желательно выносить в константы. Это делается для того, чтобы не было ошибок которые возникают при разных версиях библиотек. В файле build.gradle есть пример
Желательно вынести все версии библиотек тоже в константы как там. Пример :$rootProject.recyclerViewVersion"

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/moveid/MoveIdResponse.kt
> +        get() = "https://image.tmdb.org/t/p/w500$field"
Тут везде дублируется image URL. Если он поменяется - то придется менять по всему проекту, где-то забудется и будет баг. Поэтому лучше imageUrl тоже вынести например также как основной URL, чтобы поменять было легко.

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/TvShowsLocal.kt
> +        get() = voteAverage.div(2).toFloat()
Логика подсчета рейтинга дублируется, лучше логику не дублировать - иначе это влечет к багам в логике

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/TvShowsLocal.kt
> +        get() = voteAverage.div(2).toFloat()
Magic Number (2)

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/base/MapperDomain.kt
> +sealed interface MapperDomain {
Хорошо что сделал базовый маппер. Можно было бы еще вот так:
```

interface ViewObjectMapper<VO, DTO> {

    fun toViewObject(dto: DTO): VO

    fun toViewObject(list: Collection<DTO>): List<VO> {
        val result = ArrayList<VO>()
        list.mapTo(result) { toViewObject(it) }
        return result
    }
}

```
Таким образом, реализовав только 1 метод мы автоматом получаем и метод для коллекции и не надо в других местах делать map. Ну и базовый интерфейс как бы определят правила мапинга

В твоем варианте смущает наличие обоих методов toView/toDomain - нужны ли они будут везде? На мой взгляд лучше использовать несколько мелких интерфейсов и если нужно - то потом их использовать, чем один более крупный, об этом же приницип ISP, вот тут неплохой пример https://habr.com/ru/articles/688530/ Но не критично

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/MovieLocal.kt
> +        get() = voteAverage.div(2).toFloat()
Magic Number

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/moveid/MoveIdResponse.kt
> +        get() =field.div(2)
Magic Number

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/movies/Movie.kt
> +        get() = "https://image.tmdb.org/t/p/w500$field"
Повторяющийся URL

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/tvseries/TvShows.kt
> +        get() = "https://image.tmdb.org/t/p/w500$field"
Повторяющийся URL

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/AuthMovieApiInterceptor.kt
> +            .addHeader("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzODQ3MDk1Y2FkODQ0OWVjMWI5Y2E2MjQwZmE5MTAyYyIsIm5iZiI6MTcyMzU1MTQ2NS4wMTAzMDcsInN1YiI6IjVmZjE5NzRmMGM0YzE2MDAzZmE0YzExZi
Не надо было токен тут в открытую публиковать - это же публичный репозиторий. Для этого есть в проекте файл keystore.properties - в него нужно закинуть токен, а сам файл должен быть в .gitignore, чтобы не светить API ключами. Любой человек может взять этот ключ и использовать - а если бы API был платный то из-за кол-ва запросов могла набежать кругленькая сумма, не надо так.

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiClient.kt
> +        .addInterceptor(HttpLoggingInterceptor(CustomHttpLogging()).apply {
Вот тут можно сделать проверку Build.Config!=Release - чтобы в релизной сборке не было видно логов

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiInterface.kt
> +        @Query("language") language: String = "en-US",
Тут кстати вместо хардкода можно еще вот так сделать Locale.getDefault().toLanguageTag() вернет en-US 
Ну или хотя бы вынести эту строку в константы нужно

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiInterface.kt
> +        @Query("page") page: Int = 1,
Page я бы тоже рекомендовал вынести в константы

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +                        MovieItem(MovieMapper().toView(it)) { movie ->
Этот код одинаковый - можно вынести его в метод, а внутри метода оставить логику создания     MainCardContainer и мапинг MovieItem, а на входе метода будет только строковый ресурс и фильмы, и тогда не нужно копировать логику для 3-ех методов.

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +        if (arguments?.getInt(KEY_MOVIE_ID) != null) {
Можно попробовать через let?., тогда внизу не придется использовать оператор !!

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/res/layout/movie_details_fragment.xml
> +                android:id="@+id/movie_favourite"
На мой взгляд для лайка лучше использовать CheckBox. У него автоматически будет из коробки работа со состояниями (checked/unchecked). И создать кастомный селектор в виде пустого и закрашенного сердечка
https://stackoverflow.com/a/3193127/1462969

2024-08-15 15:25 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +                response.body()?.let {
Часто повторяется проверка  response.body()?.let, но это можно будет убрать например через compose в rx (в последнем вебинаре про Rx показывал пример)

2024-08-16 05:16 UTC, artem-inkaz commented on app/build.gradle
> +    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
+

2024-08-16 05:16 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/moveid/MoveIdResponse.kt
> +        get() = "https://image.tmdb.org/t/p/w500$field"
+

2024-08-16 05:16 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/TvShowsLocal.kt
> +        get() = voteAverage.div(2).toFloat()
+

2024-08-16 05:16 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/TvShowsLocal.kt
> +        get() = voteAverage.div(2).toFloat()
+

2024-08-16 05:20 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/MovieLocal.kt
> +        get() = voteAverage.div(2).toFloat()
+

2024-08-16 05:20 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/moveid/MoveIdResponse.kt
> +        get() =field.div(2)
+

2024-08-16 05:20 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/movies/Movie.kt
> +        get() = "https://image.tmdb.org/t/p/w500$field"
+

2024-08-16 05:20 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/tvseries/TvShows.kt
> +        get() = "https://image.tmdb.org/t/p/w500$field"
+

2024-08-16 05:20 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/network/AuthMovieApiInterceptor.kt
> +            .addHeader("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzODQ3MDk1Y2FkODQ0OWVjMWI5Y2E2MjQwZmE5MTAyYyIsIm5iZiI6MTcyMzU1MTQ2NS4wMTAzMDcsInN1YiI6IjVmZjE5NzRmMGM0YzE2MDAzZmE0YzExZi
+

2024-08-16 05:20 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiInterface.kt
> +        @Query("language") language: String = "en-US",
+

2024-08-16 05:21 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiInterface.kt
> +        @Query("page") page: Int = 1,
+

2024-08-16 06:12 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +        if (arguments?.getInt(KEY_MOVIE_ID) != null) {
+

2024-08-16 06:46 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +                        MovieItem(MovieMapper().toView(it)) { movie ->
+

2024-08-16 06:47 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/base/MapperDomain.kt
> +sealed interface MapperDomain {
+

2024-08-16 07:29 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiClient.kt
> +        .addInterceptor(HttpLoggingInterceptor(CustomHttpLogging()).apply {
+

2024-08-16 10:34 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/extensions/Funcs.kt
> +    return voteAverage.div(2).toFloat()
Magic Number

2024-08-16 10:35 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/extensions/Funcs.kt
> +    return voteAverage.div(2).toFloat()
https://refactoring.guru/ru/replace-magic-number-with-symbolic-constant

2024-08-16 10:38 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiInterface.kt
> +        @Query("language") language: String = Locale.getDefault().toLanguageTag(),
Вот это тоже повторяется) Если например поменяются требование и нужно будет как-то по-другому вычислять language, то придется опять во множестве мест менять. Поэтому лучше создать метод fun getLanguage()=Locale.getDefault().toLanguageTag() и уже его везде использовать

2024-08-16 10:38 UTC, AndroidStudentClub commented on app/src/main/res/layout/movie_details_fragment.xml
> +                android:layout_width="32dp"
Размеры лучше выносить в dimens.xml

2024-08-16 12:00 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/extensions/Funcs.kt
> +    return voteAverage.div(2).toFloat()
+

2024-08-16 12:01 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiInterface.kt
> +        @Query("language") language: String = Locale.getDefault().toLanguageTag(),
+

2024-08-16 12:05 UTC, artem-inkaz commented on app/src/main/res/layout/movie_details_fragment.xml
> +                android:layout_width="32dp"
+

2024-08-16 12:12 UTC, merged