Feature/home work 4
artem-inkaz/The_Movie_DB pull request #4
Opened 2024-08-18 12:24 UTC by artem-inkaz

Добавлен zip, PublishSubject

2024-08-19 23:04 UTC, AndroidStudentClub requested changes
Нужно посмотреть комментарии из PR 3. И здесь убрать метод start() Вынести эмиты текста в SearchBar, во фрагменте только подписываться и отправлять запрос на поиск, использовать flatMap/switchMap

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +                        Log.d(TAG, "Error: Какая-то ошибка")
Какая-то ошибка - так себе обработка ошибки, тебе же потом будет сложно понять что за ошибка, прокидывай сразу Throable/message от Exception

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +                        Log.d(TAG, "Error: Какая-то ошибка")
И еще часто видел что в OnError просто оставляешь пустые скобки - не игнорируй ошибки, оставляй там правильные логи, это сэкономит потом часы при поиске ошибок

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +        start()
Не, не, не нужно копипаcтить одни и теже методы, потом же будет очень сложно разобраться. Нужен один алгоритм который будет работать для всех.

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +        start()
Оставь только search()

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +                .retry()
Зачем retry()?

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +    private fun start() {
Предлагаю удалить этот метод, оставить только searchI() Они же почти одинаковые

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +            PublishSubject.create(ObservableOnSubscribe<String> { subscriber ->
Тут нужно решать задачу в несколько этапов
1) Вынести прокидывание текста отдельно в Seachbar (писал про это в PR 3)
2) Здесь только получить текст и уже используя этот текст делать запрос через flatMap/SwitchMap

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +                        binding.moviesRecyclerView.adapter = adapter.apply {
Логика очищения тут лишняя, если пользователь очистил поисковое поле, зачем очищать всю ленту? Но даже если и так, это не нужно делать здесь в цепочке, это нужно делать уже в OnNext после subscribe.
То есть у тебя есть onNext и вот в нем и должна тогда идти работа с UI: либо добавить в список что-то/либо очистить список. А тут логика размазывается по всей цепочке.

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +                .doOnNext {
Не, работать с лоадером лучше либо в doOnSubscribe/либо в doFinaly, тут потенциально может быть много onNext, зачем на каждый это делать? Лишняя трата ресурсов

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +                .retry()
.retry() лишний

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +                        val findMovies = MovieApiClient.apiClient.findMovies(query.toString())
Тут уже писал в PR 3 не стоит делать вложенные Rx Цепочки, используй flatMap/SwitchMap

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +                                .observeOn(AndroidSchedulers.mainThread())
Лишнее, нужно один раз выше по цепочке (в PR 3 писал про это)

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +                                    }, {}
Пустой блок в onError - залог множества потраченных часов на дебаге, лучше не оставлять пустой блок ошибки, писал про двойной onError в PR 3

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/tvshows/TvShowsFragment.kt
> +                .delay(500, TimeUnit.MILLISECONDS)
А зачем delay() ?

2024-08-19 23:04 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +                        val findMovies = MovieApiClient.apiClient.findMovies(query.toString())
Для поиска можно Single кстати вместо Observable

2024-08-20 08:33 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +                .retry()
убрал

2024-08-20 08:33 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +    private fun start() {
хорошо

2024-08-20 08:34 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +            PublishSubject.create(ObservableOnSubscribe<String> { subscriber ->
+

2024-08-20 08:34 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +                        binding.moviesRecyclerView.adapter = adapter.apply {
+

2024-08-20 08:37 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +                .retry()
+

2024-08-20 08:37 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +                        val findMovies = MovieApiClient.apiClient.findMovies(query.toString())
+

2024-08-20 08:37 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +                                .observeOn(AndroidSchedulers.mainThread())
+

2024-08-20 08:37 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +                                    }, {}
+

2024-08-20 08:50 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/ui/tvshows/TvShowsFragment.kt
> +                .delay(500, TimeUnit.MILLISECONDS)
чтобы увидеть progress bar)

2024-08-20 12:21 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +            PublishSubject.create(ObservableOnSubscribe<String> { subscriber ->
Пример реализации поиска:
1) Выдяляем логику именно эмита текста в SearchBar. Это поможет нам инкапсулировать логику. У нас есть компонент который отправляет нам текст когда мы подписываемся, как обычный EditText, только реактивный. Сама реализация этой обертки будет находиться в SearchBar

Создаем subject

`private val subject = PublishSubject.create<String>()`

Оборачиваем работу с EditText чтобы он отправлял нам текст
```
    fun onTextChanged(): Observable<String> {
        return subject
            .debounce(500, TimeUnit.MILLISECONDS)
            .map { it.trim() }
            .filter { it.length > 3 }
            .distinctUntilChanged()
    }
```

Прокидываем через subject текст в методе onAttachedToWindow

```
   override fun onAttachedToWindow() {
        super.onAttachedToWindow()
        binding.searchEditText.afterTextChanged { text ->
// Вот здесь прокидываем текст, сам по себе subject не будет эмитить если в него не вкинуть данные
            subject.onNext(text.toString())
            Timber.d("onTextChanged: $text")
            if (!text.isNullOrEmpty() && !binding.deleteTextButton.isVisible) {
                binding.deleteTextButton.visibility = View.VISIBLE
            }
            if (text.isNullOrEmpty() && binding.deleteTextButton.isVisible) {
                binding.deleteTextButton.visibility = View.GONE
            }
        }
    }
```

Теперь, уже в SearchFragment наша задача просто подписаться и сделать запрос на поиск, используя flatMap (без вложенных Rx цепочек)

 ```
 searchBinding.searchToolbar.onTextChanged() 
                .flatMap { query ->
                    MovieApiClient.apiClient.findMovies(query)
                }
                .subscribeOn(io.reactivex.schedulers.Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(
                    { result ->
                        movieList =
                            result.results.distinct().map {
                                MovieItem(MovieSearchMapper().toViewObject(it)) { movie ->
                                    openMovieDetails(
                                        movie
                                    )
                                }
                            }.toSet()
 
                        // Чтобы результаты не копились - нужно очищать адаптер перед добавлением
                        adapter.clear()
                        binding.moviesRecyclerView.adapter = adapter.apply {
                            addAll(movieList)
                        }
                    }, {
                        Timber.e("Error: ${it.message}")
                    }

```

Сравни насколько проще такой подход, здесь инкапсулирована логика работа с EditText в SearchBar

И еще момент, при переходе с FeedFragment на SearchFragment не начинался поиск сразу потому что необходимо сначала подписаться и только потом передавать тот текст который ввел пользователь при поиске, а именно:

```
 override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        val searchTerm = requireArguments().getString(KEY_SEARCH)
       // В методе search подписались 
        search()
       // Отправили в editText текст, текст тут же прокинется через subject и сразу начнется поиск
        searchBinding.searchToolbar.setText(searchTerm)
    }
```
Тогда не нужно никаких методов start() как у тебя было изначально

2024-08-21 09:20 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/SearchBar.kt
> +            .filter { it.length > 3 }
Magic Number

2024-08-21 09:20 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/SearchBar.kt
> +            Timber.d("onTextChanged: $text")
Тут лог я просто для примера оставил в комменте, думаю его можно убрать если не нужен для отладки

2024-08-21 09:20 UTC, AndroidStudentClub commented on app/src/test/java/ru/androidschool/intensiv/ExampleUnitTest.kt
> +        assertEquals(2024, currentYear)
В 2025 году тест сломается. Ну тут смысла особо в этом тесте нет, потому что ты тестируешь библиотченый метод calendar.get(Calendar.YEAR), а зачем его тестировать? Тестировать нужно свою логику. Вот если бы у тебя была логика на основе года, то тогда смысл в тесте был бы. Ну например подсчет возраста пользователя в зависимости от даты рождения - то есть это уже твой код, который ты и написал и тестируешь.

2024-08-21 09:22 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/tvshows/TvShowsFragment.kt
> +                .delay(500, TimeUnit.MILLISECONDS)
Progress Bar в любом случае будет виден на время работы сетевого запроса. А так ты добавляешь лишнее время чтобы пользователь ждал. Progress Bar можно выставить например в методе doOnSubscribe() и скрывать в doFinally()

2024-08-21 09:55 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/ui/SearchBar.kt
> +            .filter { it.length > 3 }
+

2024-08-21 09:56 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/ui/SearchBar.kt
> +            Timber.d("onTextChanged: $text")
оставлю для примера

2024-08-21 09:59 UTC, artem-inkaz commented on app/src/test/java/ru/androidschool/intensiv/ExampleUnitTest.kt
> +        assertEquals(2024, currentYear)
Закомментил

2024-08-21 10:07 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/ui/tvshows/TvShowsFragment.kt
> +                .delay(500, TimeUnit.MILLISECONDS)
подправил

2024-08-21 11:00 UTC, merged