[home_work_7] add Clean and MVP Presenter for TvShow
artem-inkaz/The_Movie_DB pull request #7
Opened 2024-09-07 14:59 UTC by artem-inkaz

2024-09-10 06:54 UTC, AndroidStudentClub requested changes

2024-09-10 06:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/actor/ActorFromApi.kt
> +interface ActorFromApi {
Я бы название предложил чуть более ясное, например ActorsDataSource

2024-09-10 06:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/actor/ActorFromApi.kt
> +    fun getActorsFromMovie(id: MovieId): Single<MoveIdCreditsResponse>
А здесь getActorsByMovieId например

2024-09-10 06:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/actor/ActorFromApiImpl.kt
> +class ActorFromApiImpl : ActorFromApi {
А тут уже ActorsNetworkDataSource, impl используется когда прямо вообще сложно придумать название реализации, а тут вроде ясно: есть общий датасорс и есть частная реализация для работы с сетью

2024-09-10 06:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/actor/ActorFromApiImpl.kt
> +        return MovieApiClient.apiClient.getMovieIdCredits(id)
API client лучше передавать в качестве аргумента, а так получается жесткая связь подменить моком для теста например будет невозможно

2024-09-10 06:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/movie/MovieFromApi.kt
> +    fun getNowPlayingMovies(): Single<MoviesResponse>
Не, зачем делать 3 одинаковых метода в этом интерфейсе? А если нам на главной нужно будет 20 разных типов то по этой логике придется добавлять еще 17 методов итп, хотя они же все делают одно и тоже. Лучше создать один метод getMovies в интерфейсе и потом сделать 3 разных реализации ( для популярных, top rated итд)

2024-09-10 06:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/movie/MovieFromApiImpl.kt
> +    override fun getNowPlayingMovies(): Single<MoviesResponse> {
Я бы предложил сделать 3 разных маленьких реализации чем одна большая с 3 одинаковыми методами. Тут слишком жирный интерфейс реализуется, я бы предложил 1 метод в интерфейсе и 3 разных реализации одного и того же интерфейса. Ну и для деталей тоже отдельный интерфейс

2024-09-10 06:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/movie/MovieFromApiImpl.kt
> +        return MovieApiClient.apiClient.getUpComingMovies()
Предложил бы передавать movie api client в качестве аргумента

2024-09-10 06:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/tvshows/TvShowsFromApi.kt
> +interface TvShowsFromApi {
Я бы предложил название TvShowsDataSource. Название интерфейса в идеале должно быть общим а реализации более конкретная. Как DataSource а у него уже реализации LocalDataSource, RemoteDataSource etc

2024-09-10 06:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/storage/ActorStorageRepositoryImpl.kt
> +    private val moviesDB = MoviesDataBase.instance.getActorDao()
Лучше передавать внешние зависимости отдельно в аргументах, так будет проще тестировать и код будет менее связный. И DI проще будет прикрутить

2024-09-10 06:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/storage/ActorStorageRepositoryImpl.kt
> +    private val actorMapper = ActorMapper()
И с Мапером тоже лучше его передавать

2024-09-10 06:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/storage/GenreStorageRepositoryImpl.kt
> +    private val moviesDB = MoviesDataBase.instance.getGenreDao()
Передавать через конструктор

2024-09-10 06:54 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/storage/GenreStorageRepositoryImpl.kt
> +import ru.androidschool.intensiv.domain.datasource.GenreStorageRepository
Тут репозиторий находится в datasource я бы предложил оставить package datasource только в data слое а тут использовать repository

2024-09-10 06:57 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/presentation/feed/FeedFragment.kt
> +                        RepositoryHolder.repositoryMovieFromStorage().insertAll(moviesLocalGroupList)
Тут лучше use case использовать

2024-09-12 03:06 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/actor/ActorFromApi.kt
> +interface ActorFromApi {
++

2024-09-12 03:06 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/actor/ActorFromApi.kt
> +    fun getActorsFromMovie(id: MovieId): Single<MoveIdCreditsResponse>
++

2024-09-12 03:07 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/actor/ActorFromApiImpl.kt
> +class ActorFromApiImpl : ActorFromApi {
++

2024-09-12 03:10 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/actor/ActorFromApiImpl.kt
> +        return MovieApiClient.apiClient.getMovieIdCredits(id)
++

2024-09-12 03:27 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/movie/MovieFromApi.kt
> +    fun getNowPlayingMovies(): Single<MoviesResponse>
++

2024-09-12 03:28 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/movie/MovieFromApiImpl.kt
> +    override fun getNowPlayingMovies(): Single<MoviesResponse> {
++

2024-09-12 03:29 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/movie/MovieFromApiImpl.kt
> +        return MovieApiClient.apiClient.getUpComingMovies()
++

2024-09-12 03:50 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/api/tvshows/TvShowsFromApi.kt
> +interface TvShowsFromApi {
++

2024-09-12 03:56 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/storage/ActorStorageRepositoryImpl.kt
> +    private val moviesDB = MoviesDataBase.instance.getActorDao()
++

2024-09-12 04:01 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/storage/ActorStorageRepositoryImpl.kt
> +    private val actorMapper = ActorMapper()
++

2024-09-12 04:01 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/data/datasource/storage/GenreStorageRepositoryImpl.kt
> +    private val moviesDB = MoviesDataBase.instance.getGenreDao()
++

2024-09-12 06:03 UTC, artem-inkaz commented on app/src/main/java/ru/androidschool/intensiv/presentation/feed/FeedFragment.kt
> +                        RepositoryHolder.repositoryMovieFromStorage().insertAll(moviesLocalGroupList)
++

2024-09-12 15:47 UTC, merged